@startuml

fsIn -> rawSource : read files

rawSource : path
rawSource : rawContent


rawSource --> articleSource : parse

articleSource: rawMeta
articleSource: markup
articleSource: rawSource↑

note right of articleSource
	Discern collectables by that point?

	Then again, static pages differ by:
	- collectability
	- templates
	- ?
end note

articleSource --> article: accept to model

article: id
article: URL
article: meta (valid)
article: markup
article: excerpt
article: source: articleSource↑

note right of article
	`article` is in the broadest, html5 sense
	Markup is just a string if we’re using Monaco
	or smth for editing. Later we can switch to an
	editor that works with a tree model.
end note


article-->renderedPage: render

note right of renderedPage
	Pre-render? Should model somehow be adopted to views?

	Should templates get rendered html, for instance?
	Not if the views can switch from rendered html to Monaco.
end note

collection-->renderedPage
note right of collection: TODO


renderedPage-->fsOut: write

fsOut --> [*]

@enduml
